shared:
    image: node:6
jobs:
    main:
        steps:
            - install: npm install
            - test: npm test
        requires:
            - ~pr
            - ~commit
    publish:
        steps:
            - print: echo Starting publish job!
        requires:
            - main
